#!/bin/sh

# A file name (the name of a Coq module) must be provided on the command line.

# We remove any leading ".v" or "." suffix, so it is OK if the filename ends
# in ".v", ".", or has no extension at all.

# Here, we rebuild just this module.

# See also the script "./prepare".

BASENAME=`basename $1 .v`
BASENAME=`basename $BASENAME .`
rm -f targets
echo $BASENAME.vo > targets
make targets
rm -f targets
